addons:
    ssh_known_hosts: 185.26.156.50

language: node_js
node_js:
- node

before_install:
- sudo apt-get -qq update
- sudo apt-get install rsync
- openssl aes-256-cbc -K $encrypted_af70c45caba8_key -iv $encrypted_af70c45caba8_iv -in priv_rsa.enc -out /tmp/priv_rsa -d
- chmod 600 /tmp/priv_rsa

before_script: # commands to run before the build step
- npm install -g --silent @angular/cli

script: 
- cd backend && npm install && npm test
- cd ../frontend/frontend-flatgame && npm install
- ng build --prod --bh /

deploy:
    provider: script
    skip_cleanup: true
    script: rsync -r -e 'ssh -i /tmp/priv_rsa' --delete-after $TRAVIS_BUILD_DIR/backend/ $USER@$HOST:~/node/ -v --exclude=config && rsync -r -e 'ssh -i /tmp/priv_rsa' --delete-after $TRAVIS_BUILD_DIR/frontend/frontend-flatgame/dist/ $USER@$HOST:/var/www/virtual/$USER/flatgame.joblock.de/ -v
    on:
        branch: master
