addons:
    ssh_known_hosts: 185.26.156.50

language: node_js

before_install:
- openssl aes-256-cbc -K $encrypted_af70c45caba8_key -iv $encrypted_af70c45caba8_iv -in priv_rsa.enc -out /tmp/priv_rsa -d
- chmod 600 /tmp/priv_rsa

script: 
- cd backend && npm install && npm test
- cd ../frontend/frontend-flatgame
- ng build --prod

deploy:
    provider: script
    skip_cleanup: true
    script: 
    - rsync -r -e 'ssh -i /tmp/priv_rsa' --delete-after $TRAVIS_BUILD_DIR/backend/ $USER@$HOST:~/node/ -v --exclude=config
    - rsync -r -e 'ssh -i /tmp/priv_rsa' --delete-after $TRAVIS_BUILD_DIR/frontend/frontend-flatgame/dist $USER@$HOST:~/angular/ -v
    on:
        branch: master
